### ISSUE TITLE
ApiKey Configuration 

### ISSUE THREAD

**Issue by xakernaoffe** [mdedetrich/stripe-scala#2]
I've added this library to play framework project. When i am running it i am getting this error:

```
Configuration error: Configuration error[application.conf @ jar:file:/Users/macos/.ivy2/cache/org.mdedetrich/stripe-scala_2.11/jars/stripe-scala_2.11-1.0.0-SNAPSHOT.jar!/application.conf: 5: Could not resolve substitution to a value: ${STRIPE_APIKEY}]
    at play.api.Configuration$.configError(Configuration.scala:178)
    at play.api.Configuration$.load(Configuration.scala:103)
    at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:203)
    at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
    at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
    at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at play.runsupport.Reloader$.startDevMode(Reloader.scala:223)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
    at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

How configure library to pick this key from play application config file?

**Comment by mdedetrich** [comment]
The easiest way would be to probably set an environment variable (this is recommended practice since you usually do not want to put secret application keys into an `application.conf` file).

You can do so by doing

``` sh
export STRIPE_APIKEY = mykeyhere
```

in the shell before launching the play app. Alternately you can also specify the argument as a java system setting (i.e. `java -Dstripe-scala.apiKey=mykeyhere`)

Alternately if you really want to use the play's `application.conf`, put something like the following in your application.conf

```
stripe-scala {
  apiKey = mykeyhere
}
```

If the above doesn't work then you may need to the the process here http://stackoverflow.com/a/24156494/1519631, and with that you need to provide your own implicit instance of `org.mdedetrich.stripe.ApiKey`

Let me know if you still have issues

**Comment by mdedetrich** [comment]
I am going to close this for now, reopen it if its still an issue
