### ISSUE TITLE
cats-core version conflicts - upgrading circe-core to 0.9.2

### ISSUE THREAD

**Issue by onmomo** [mdedetrich/stripe-scala#42]
We get a dependency conflict during json decoding probably because stripe-scala transitively links in an older version of cats-core:0.9.1 via circe-core:0.8.0. An update to circe-core:0.9.2 would eventually solve the issue because it links cats-core:1.0.1, the version we do require.

This happens if we call `Customers.get`
```
java.lang.NoClassDefFoundError: cats/functor/Invariant
	at io.circe.Decoder$.<init>(Decoder.scala:776)
	at io.circe.Decoder$.<clinit>(Decoder.scala)
	at org.mdedetrich.stripe.v1.Customers$.<init>(Customers.scala:42)
	at org.mdedetrich.stripe.v1.Customers$.<clinit>(Customers.scala)
	at org.acme.id.app.http.api.services.stripepayment.domain.PaymentController.getSubscriptions(PaymentController.scala:67)
```

Upgrading to circe-core:0.9.2 could solve the issue, not sure about any side effects, though.

**Comment by leonardehrenfried** [comment]
Hi,

thanks for reporting and this prompted my to give this project a 2018 upgrade where I will also bump the circe version. Bumping the version shouldn't be a huge problem as there are tons of tests.

Will add a link when I open a PR.

**Comment by leonardehrenfried** [comment]
https://github.com/mdedetrich/stripe-scala/pull/43
